## Creating Native, Roman, English triplets

In [67]:
import pandas as pd

In [68]:
ba = pd.read_csv("abhijnaanam_triplets.csv")

In [69]:
bpcc = pd.read_csv("transliterated_bpcc.csv")

In [70]:
ba.head()

,id,native,roman,label,script,source,english_random_sentence
0,as_2,ইমান উপকাৰী ইনচুলিনৰো যে কোনো পাৰ্শ্বক্ৰিয়া ন...,imaan upokari insulinoru je kunu parswokriya n...,Assamese,Bengali,Dakshina,State Chief Minister Manohar Parrikar and BJP ...
1,as_3,কৃত্ৰিম দণ্ডৰ বেলিকা পিতৃ - মাতৃয়ে পাৰিবাৰিক ...,kritrim dondor belika pitri - matriye paribari...,Assamese,Bengali,Dakshina,"So they will be overturned into Hellfire, they..."
2,as_4,আৰক্ষীয়ে হাবিলদাৰজনক অৰ্ধচেতন অৱস্থাত উদ্ধাৰ ...,arokhyiye habildarjonok ordhoseton owosthat ud...,Assamese,Bengali,Dakshina,"And We wronged them not, but they wronged them..."
3,as_5,হাজো সুৰেন দাস মহাবিদ্যালয়ৰ ছাত্র একতা সভাৰ ন...,haaju xuren daax mohabidyaloyor saatro ekota x...,Assamese,Bengali,Dakshina,Gurdwara Darbar Sahib Kartarpur is situated in...
4,as_6,ইয়াৰোপৰি ব্যক্তিৰ মনৰ ভাৰসাম্য ৰক্ষা কৰি চলি ...,iyarupori byoktir monor bharxamyo rokhya kori ...,Assamese,Bengali,Dakshina,Did God just turn a blind eye to the situation?

In [71]:
bpcc.head()

,src_lang,tgt_lang,src,tgt,Roman
0,eng_Latn,kas_Arab,"He bickers with the maids, harrows his hapless...",سُہ چُھ داین سۭتۍ لَڑٲے کَران، پنٛنِس مُصیٖبت ...,"snh chnh dain snty lnnae knran, pnnnns mnninbt..."
1,eng_Latn,kas_Arab,"The Nizam, seeking to deflect the Company from...",نظامَن اوس حیدر علی یَس سٕتہِ ،کمپنی شٗمٲلی س...,"nnamnn aus nidr nli ins snthn ,kmpni shnmali ..."
2,eng_Latn,kas_Arab,In 1766 Mysore began to become drawn into terr...,1766 منٛز ہیو٘تٗن میسور حیدرآبادٕ کِس نظامس ت...,1766 mnnz hiuntnn misur nidrnbadn kns nnams t...
3,eng_Latn,kas_Arab,"Ray began to make illustrations for it, as wel...",رے ین خمرِ امہِ باپت تصویر تیار كِرٕنہِ ،تہِ...,"re in khmrn amhn bapt tnuir tiar knrnnhn ,th..."
4,eng_Latn,kas_Arab,"Prithviraj, who was a minor at the time, ascen...",پرتھوی راج یُس تَمہِ وِزِ لو٘كٗٹ اوس، بِیوٗٹھ...,"prthui raj ins tnmhn unzn lunknn aus, bniunnh..."

In [72]:
label_to_script = {
    'asm_Beng': 'Bengali',
    'ben_Beng': 'Bengali',
    'brx_Deva': 'Devanagari',
    'doi_Deva': 'Devanagari',
    'gom_Deva': 'Devanagari',
    'guj_Gujr': 'Gujarati',
    'hin_Deva': 'Devanagari',
    'kan_Knda': 'Kannada',
    'kas_Arab': 'Arabic',        # Kashmiri in Arabic script
    'mai_Deva': 'Devanagari',
    'mal_Mlym': 'Malayalam',
    'mar_Deva': 'Devanagari',
    'mni_Mtei': 'Meetei-Mayek',
    'npi_Deva': 'Devanagari',
    'ory_Orya': 'Oriya',
    'pan_Guru': 'Gurmukhi',
    'san_Deva': 'Devanagari',
    'sat_Olck': 'Olchik',
    'snd_Deva': 'Devanagari',    # Sindhi in Devanagari version
    'tam_Taml': 'Tamil',
    'tel_Telu': 'Telugu',
    'urd_Arab': 'Arabic'         # Urdu in Arabic script
}

In [73]:
label_to_lang = {
    'asm_Beng': 'Assamese',
    'ben_Beng': 'Bangla',
    'brx_Deva': 'Bodo',
    'doi_Deva': 'Dogri',
    'gom_Deva': 'Konkani',
    'guj_Gujr': 'Gujarati',
    'hin_Deva': 'Hindi',
    'kan_Knda': 'Kannada',
    'kas_Arab': 'Kashmiri',
    'mai_Deva': 'Maithili',
    'mal_Mlym': 'Malayalam',
    'mar_Deva': 'Marathi',
    'mni_Mtei': 'Manipuri',
    'npi_Deva': 'Nepali',
    'ory_Orya': 'Oriya',
    'pan_Guru': 'Punjabi',
    'san_Deva': 'Sanskrit',
    'sat_Olck': 'Santali',
    'snd_Deva': 'Sindhi',
    'tam_Taml': 'Tamil',
    'tel_Telu': 'Telugu',
    'urd_Arab': 'Urdu'
}

In [74]:
bpcc['label'] = bpcc['tgt_lang'].map(label_to_lang)
bpcc['script'] = bpcc['tgt_lang'].map(label_to_script)

In [75]:
ba['script'] = ba['script'].replace(
    {'Perso-Arabic': 'Arabic', 'Perso_Arabic': 'Arabic'}
)

In [76]:
bpcc.drop(["src_lang", "tgt_lang", "src"], axis=1, inplace=True)
bpcc = bpcc.rename(columns={'tgt': 'native', 'Roman': 'roman'})

In [77]:
from datasets import load_dataset
import random

langs = ["hi", "bn", "ta", "ml", "te", "gu", "mr", "pa", "or", "kn", "as"]
english_sentences = []

for lang in langs:
    try:
        print(f"Loading {lang} split from Samanantar...")
        ds = load_dataset("ai4bharat/samanantar", lang, split="train[:200000]")

        # Filter sentences that are strings and have between 10 and 50 words
        filtered = [
            row["src"] for row in ds
            if isinstance(row["src"], str)
            and 10 <= len(row["src"].split()) <= 50
        ]

        english_sentences.extend(filtered)
        print(f"Loaded {len(filtered):,} valid English sentences for {lang}")

    except Exception as e:
        print(f"Skipping {lang} due to error: {e}")

print(f"Total English sentences collected: {len(english_sentences):,}")

# Sanity check
if not english_sentences:
    raise RuntimeError("No English sentences collected! Check dataset structure or filtering criteria.")

# Randomly assign one English sentence to each row
bpcc["english_random_sentence"] = random.choices(
    english_sentences, k=len(bpcc)
)

print("Added 'english_random_sentence' column from Samanantar dataset.")

Loading hi split from Samanantar...
Loaded 129,740 valid English sentences for hi
Loading bn split from Samanantar...
Loaded 81,276 valid English sentences for bn
Loading ta split from Samanantar...
Loaded 81,614 valid English sentences for ta
Loading ml split from Samanantar...
Loaded 75,598 valid English sentences for ml
Loading te split from Samanantar...
Loaded 68,754 valid English sentences for te
Loading gu split from Samanantar...
Loaded 78,150 valid English sentences for gu
Loading mr split from Samanantar...
Loaded 85,900 valid English sentences for mr
Loading pa split from Samanantar...
Loaded 105,667 valid English sentences for pa
Loading or split from Samanantar...
Loaded 86,231 valid English sentences for or
Loading kn split from Samanantar...
Loaded 64,600 valid English sentences for kn
Loading as split from Samanantar...
Loaded 66,152 valid English sentences for as
Total English sentences collected: 923,682
Added 'english_random_sentence' column from Samanantar dataset.

In [78]:
ba.drop("source", axis=1, inplace=True)

In [79]:
combined = pd.concat([ba, bpcc], axis=0, ignore_index=True)
combined.head()

,id,native,roman,label,script,english_random_sentence
0,as_2,ইমান উপকাৰী ইনচুলিনৰো যে কোনো পাৰ্শ্বক্ৰিয়া ন...,imaan upokari insulinoru je kunu parswokriya n...,Assamese,Bengali,State Chief Minister Manohar Parrikar and BJP ...
1,as_3,কৃত্ৰিম দণ্ডৰ বেলিকা পিতৃ - মাতৃয়ে পাৰিবাৰিক ...,kritrim dondor belika pitri - matriye paribari...,Assamese,Bengali,"So they will be overturned into Hellfire, they..."
2,as_4,আৰক্ষীয়ে হাবিলদাৰজনক অৰ্ধচেতন অৱস্থাত উদ্ধাৰ ...,arokhyiye habildarjonok ordhoseton owosthat ud...,Assamese,Bengali,"And We wronged them not, but they wronged them..."
3,as_5,হাজো সুৰেন দাস মহাবিদ্যালয়ৰ ছাত্র একতা সভাৰ ন...,haaju xuren daax mohabidyaloyor saatro ekota x...,Assamese,Bengali,Gurdwara Darbar Sahib Kartarpur is situated in...
4,as_6,ইয়াৰোপৰি ব্যক্তিৰ মনৰ ভাৰসাম্য ৰক্ষা কৰি চলি ...,iyarupori byoktir monor bharxamyo rokhya kori ...,Assamese,Bengali,Did God just turn a blind eye to the situation?

In [80]:
combined.label.value_counts()

label
Marathi      416198
Bangla       406926
Gujarati     404834
Telugu       397295
Malayalam    396990
Hindi        394989
Tamil        390964
Kannada      387124
Oriya        386734
Assamese     378647
Nepali       355545
Punjabi      308963
Sanskrit     299108
Maithili     255303
Bodo         213497
Urdu         204822
Kashmiri     194035
Konkani      182767
Sindhi       169608
Dogri        134100
Manipuri     108732
Santali      100345
Name: count, dtype: int64

In [81]:
combined.to_csv("combined.csv", index=False)

In [82]:
sampled_dfs = []

for lang, group in combined.groupby("label"): 
    sampled = group.sample(n=100_345, random_state=42)
    sampled_dfs.append(sampled)

combined_balanced = pd.concat(sampled_dfs, ignore_index=True)
print("Samples per language (after undersampling):")
print(combined_balanced["label"].value_counts())

# Calculate size in bytes → MB / GB
df_size_bytes = combined_balanced.memory_usage(deep=True).sum()
df_size_mb = df_size_bytes / (1024 ** 2)
df_size_gb = df_size_bytes / (1024 ** 3)

print(f"\nTotal samples: {len(combined_balanced):,}")
print(f"Languages included: {combined_balanced['label'].nunique()}")
print(f"DataFrame size: {df_size_mb:.2f} MB ({df_size_gb:.3f} GB)")

Samples per language (after undersampling):
label
Assamese     100345
Bangla       100345
Bodo         100345
Dogri        100345
Gujarati     100345
Hindi        100345
Kannada      100345
Kashmiri     100345
Konkani      100345
Maithili     100345
Malayalam    100345
Manipuri     100345
Marathi      100345
Nepali       100345
Oriya        100345
Punjabi      100345
Sanskrit     100345
Santali      100345
Sindhi       100345
Tamil        100345
Telugu       100345
Urdu         100345
Name: count, dtype: int64

Total samples: 2,207,590
Languages included: 22
DataFrame size: 1642.29 MB (1.604 GB)

In [83]:
combined_balanced = combined_balanced[['native','roman','english_random_sentence']].rename(
    columns={'english_random_sentence': 'english'})
combined_balanced.to_csv("triplet_nre.csv", index=False)
print("NRE(type A) triplets are saved")

NRE(type A) triplets are saved

In [84]:
combined_balanced.head()

,native,roman,english
0,২ ) সম্পূৰ্ণৰূপে মদ খোৱা বাৰণ কৰা ।,uu ) xompurnorupe modd khuwa baaron koraa .,The matter will be heard by a three-member ben...
1,এইটো হয়তো অৱশেষত আপোনাৰ বাবে প্ৰয়োজনীয় সমাধ...,eiṭo haẏato avaśeṣata āponāra bābe praẏojanīẏ...,It is proper for us to want to use our life in...
2,"কিন্তু, অপোনাৰ কফি বনোৱা মূল লক্ষ্যটোত উপনীত হ...","kintu, aponāra kaphi banovā mūla lakṣyaṭota up...","ZTE has launched a new flagship smartphone, th..."
3,অমল নাৰায়ণ পাটোৱাৰী,omol narayan patuwary,Dont delay execution of convicts: Nirbhayas mo...
4,মহাজাগতিক ৰীতি-নীতি বৈদিক প্ৰথা বা হিন্দু ধৰ্ম...,mahājāgatika rīti-nīti baidika prathā bā hindu...,The film is directed by Kishore Reddy and prod...

## Creating triplets with Native pair of Same language, Native of different language

In [85]:
# =============== Sampling 100k sentences for each class from same dataframe =============

sampled_dfs = []

for lang, group in combined.groupby("label"): 
    sampled = group.sample(n=100_345, random_state=24)
    sampled_dfs.append(sampled)

combined_balanced = pd.concat(sampled_dfs, ignore_index=True)
print(combined_balanced["label"].value_counts())

label
Assamese     100345
Bangla       100345
Bodo         100345
Dogri        100345
Gujarati     100345
Hindi        100345
Kannada      100345
Kashmiri     100345
Konkani      100345
Maithili     100345
Malayalam    100345
Manipuri     100345
Marathi      100345
Nepali       100345
Oriya        100345
Punjabi      100345
Sanskrit     100345
Santali      100345
Sindhi       100345
Tamil        100345
Telugu       100345
Urdu         100345
Name: count, dtype: int64

In [86]:
df = combined_balanced[['native', 'label']]
df.head()

                                              native     label
0                         ই ৯ - ১০ মাহত গাভিনী হয় ।  Assamese
1  কিতাপখনৰ বেটুপাতত এটুকুৰা ছিগা ৰঙা ফিতাৰ ছবি আ...  Assamese
2  পাষাণ পিতৃয়ে পুত্ৰৰ পঢ়া কিতাপ - বহী পৰ্যন্ত ...  Assamese
3  চৰণ পাদুকাৰ দৰ্শন কৰাৰ পিছত তীৰ্থযাত্ৰীসকলে অৰ...  Assamese
4  কম - বেছি পৰিমাণে আমাৰ বেছিভাগৰে শালমইনা হোৱা ...  Assamese

In [87]:
import pandas as pd
import numpy as np
from tqdm import tqdm

tqdm.pandas()

# --- Step 1: Group once by label (fast) ---
class_sentences = {
    label: group['native'].values
    for label, group in tqdm(df.groupby('label'), desc="Grouping sentences by label")
}

labels = list(class_sentences.keys())

# --- Step 2: Compute triplet counts per label (stratified like stratify=y) ---
class_counts = df['label'].value_counts(normalize=True).to_dict()
total_triplets = len(df)
triplets_per_class = {
    label: int(round(class_counts[label] * total_triplets))
    for label in labels
}

# --- Step 3: Generate stratified + nested-balanced triplets ---
triplet_chunks = []

for label in tqdm(labels, desc="Generating balanced nested triplets by class"):
    sentences = class_sentences[label].copy()
    np.random.shuffle(sentences)

    total_needed = triplets_per_class[label]
    n_other = len(labels) - 1
    per_negative_label = total_needed // n_other
    remainder = total_needed % n_other

    # ensure even pairing for A-B
    if len(sentences) < 2:
        continue

    # Repeat if not enough to cover all pairs
    needed_pairs = total_needed
    if len(sentences) < needed_pairs * 2:
        sentences = np.tile(sentences, int(np.ceil((needed_pairs * 2) / len(sentences))))
    if len(sentences) % 2 != 0:
        sentences = sentences[:-1]

    # Create large shuffled A/B pool
    A_pool = sentences[::2]
    B_pool = sentences[1::2]

    ptr = 0
    chunks_per_label = []

    for neg_label in labels:
        if neg_label == label:
            continue

        # Determine how many pairs to take for this negative label
        n_samples = per_negative_label + (1 if remainder > 0 else 0)
        remainder -= 1 if remainder > 0 else 0

        # Slice A/B pairs from the shuffled pool
        A = A_pool[ptr:ptr + n_samples]
        B = B_pool[ptr:ptr + n_samples]
        ptr += n_samples

        # Sample negatives (C) from this specific negative label
        neg_sentences = class_sentences[neg_label]
        C = np.random.choice(neg_sentences, size=n_samples, replace=len(neg_sentences) < n_samples)

        # Combine this chunk
        chunk = np.column_stack([A, B, C, np.full(len(A), label, dtype=object)])
        chunks_per_label.append(chunk)

    # Merge chunks for this label
    if chunks_per_label:
        triplet_chunks.append(np.vstack(chunks_per_label))

# --- Step 4: Combine all triplets ---
triplet_array = np.vstack(triplet_chunks)
triplet_df = pd.DataFrame(triplet_array, columns=['A', 'B', 'C', 'label'])

# --- Step 5: Shuffle and trim ---
triplet_df = triplet_df.sample(frac=1, random_state=42).reset_index(drop=True)
triplet_df = triplet_df.iloc[:len(df)]

# --- Step 6: Verify class and negative balance ---
print(f"\nGenerated {len(triplet_df):,} balanced triplets (same as original rows)")
print("Triplet anchor class distribution:")
print(triplet_df['label'].value_counts(normalize=True).round(3))

# Build a mapping from sentence -> label (fast)
sentence_to_label = {}
for label, sentences in class_sentences.items():
    for s in sentences:
        sentence_to_label[s] = label

# Map C sentences to labels quickly
neg_series = triplet_df['C'].map(sentence_to_label)

print("\nNegative sentence class distribution (should be roughly uniform per anchor):")
print(neg_series.value_counts(normalize=True).round(3))

triplet_df.head()

Grouping sentences by label: 100%|██████████| 22/22 [00:00<00:00, 49.23it/s]
Generating balanced nested triplets by class: 100%|██████████| 22/22 [00:00<00:00, 22.34it/s]

Generated 2,207,590 balanced triplets (same as original rows)
Triplet anchor class distribution:
label
Bodo         0.045
Bangla       0.045
Malayalam    0.045
Urdu         0.045
Tamil        0.045
Marathi      0.045
Hindi        0.045
Kannada      0.045
Telugu       0.045
Punjabi      0.045
Kashmiri     0.045
Oriya        0.045
Sindhi       0.045
Manipuri     0.045
Sanskrit     0.045
Dogri        0.045
Maithili     0.045
Nepali       0.045
Konkani      0.045
Santali      0.045
Gujarati     0.045
Assamese     0.045
Name: proportion, dtype: float64

Negative sentence class distribution (should be roughly uniform per anchor):
C
Gujarati     0.045
Assamese     0.045
Dogri        0.045
Bangla       0.045
Hindi        0.045
Kannada      0.045
Bodo         0.045
Kashmiri     0.045
Marathi      0.045
Sindhi       0.045
Maithili     0.045
Punjabi      0.045
Oriya        0.045
Malayalam    0.045
Urdu         0.045
Nepali       0.045
Sanskrit     0.045
Manipuri     0.045
Tamil        0.045
Konkani      0.045
Telugu       0.045
Santali      0.045
Name: proportion, dtype: float64

,A,B,C,label
0,1987 एक्टनि थि आयेनारि सिबिथाय बिगोमानि सिङाव ...,बुथारनाय हान्जाखौ पुलिसा मिथिनो मोनदोंब्लाबो र...,پولڪو,Bodo
1,ভেরী অঞ্চল,খেলার দু'মিনিটেরও কম সময়ের মধ্যে একটি ৮১ গজ অ...,اگرٕ مگرن ہنز سخاوت تٲے تٲے,Bangla
2,ഒരുകൂട്ടർ വിജയിക്കുമ്പോൾ മറുവശത്തിന് ഇതെന്താണ്...,ഗോൾഡൻ വിസ ( യു എ ഇ ),আধুনিক যুগত সমকামিতা পশ্চিমীয়া দেশসমূহত অধিক ...,Malayalam
3,یہ خطبہ تاریخ اسلام کا بہت ہی فصیح اور طاقت ور...,بیرون ملک مجموعہ سترہ دنوں میں 7.25 ملین ڈالر ...,ओह्‌‌ अपनी सभनें शा लौह्‌‌‌की धीऽ दी कड़माई लं...,Urdu
4,காலை 10 மணியிலிருந்து பிற்பகல் 3 மணி வரை இருக்...,ஒரு பேய் அந்த பயணியின் உடலின் அனைத்து பாகங்களை...,ھي سنڌ جو ناميارو ليکڪ ڪهاڻيڪار، ڊرامه نگار، ش...,Tamil

In [88]:
# Count duplicate pairs (A, B) per class
duplicate_pair_counts = triplet_df.groupby('label').apply(
    lambda g: pd.Series(zip(g['A'], g['B'])).duplicated().sum(), include_groups=False
)

# Percentage of duplicates per class
duplicate_pair_pct = triplet_df.groupby('label').apply(
    lambda g: pd.Series(zip(g['A'], g['B'])).duplicated().mean() * 100, include_groups=False
)

# Combine results
dup_pair_df = pd.DataFrame({
    'dup_pairs_count': duplicate_pair_counts,
    'dup_pairs_pct': duplicate_pair_pct
})

print(dup_pair_df)

           dup_pairs_count  dup_pairs_pct
label
Assamese                 0       0.000000
Bangla                   0       0.000000
Bodo                     0       0.000000
Dogri                    8       0.007972
Gujarati                13       0.012955
Hindi                    0       0.000000
Kannada                  0       0.000000
Kashmiri              2143       2.135632
Konkani                 15       0.014948
Maithili                 1       0.000997
Malayalam                0       0.000000
Manipuri                 8       0.007972
Marathi                  2       0.001993
Nepali                   0       0.000000
Oriya                    0       0.000000
Punjabi                  1       0.000997
Sanskrit                 4       0.003986
Santali                  0       0.000000
Sindhi                   0       0.000000
Tamil                    4       0.003986
Telugu                  55       0.054811
Urdu                     0       0.000000

In [89]:
triplet_df

,A,B,C,label
0,1987 एक्टनि थि आयेनारि सिबिथाय बिगोमानि सिङाव ...,बुथारनाय हान्जाखौ पुलिसा मिथिनो मोनदोंब्लाबो र...,پولڪو,Bodo
1,ভেরী অঞ্চল,খেলার দু'মিনিটেরও কম সময়ের মধ্যে একটি ৮১ গজ অ...,اگرٕ مگرن ہنز سخاوت تٲے تٲے,Bangla
2,ഒരുകൂട്ടർ വിജയിക്കുമ്പോൾ മറുവശത്തിന് ഇതെന്താണ്...,ഗോൾഡൻ വിസ ( യു എ ഇ ),আধুনিক যুগত সমকামিতা পশ্চিমীয়া দেশসমূহত অধিক ...,Malayalam
3,یہ خطبہ تاریخ اسلام کا بہت ہی فصیح اور طاقت ور...,بیرون ملک مجموعہ سترہ دنوں میں 7.25 ملین ڈالر ...,ओह्‌‌ अपनी सभनें शा लौह्‌‌‌की धीऽ दी कड़माई लं...,Urdu
4,காலை 10 மணியிலிருந்து பிற்பகல் 3 மணி வரை இருக்...,ஒரு பேய் அந்த பயணியின் உடலின் அனைத்து பாகங்களை...,ھي سنڌ جو ناميارو ليکڪ ڪهاڻيڪار، ڊرامه نگار، ش...,Tamil
...,...,...,...,...
2207585,"அம்மா! இன்னக்கி நான் லைன்ல சரியா நிக்கலன்னு, ...",காயத்தின் மீது வீக்கம் .,اس وائرس کے گیانا میں 11 مارچ 2020 کو پہنچنے ک...,Tamil
2207586,ਹੈਰੀ ਪੌਟਰ ਐਂਡ ਦ ਗੌਬਲੈਟ ਔਫ਼ ਫ਼ਾਇਰ,ਚੱਕ ਕਰੇ ਖਾਂ,यसले उनीहरूलाई आफ्ना नानीहरूको राम्रो हेरचाह ग...,Punjabi
2207587,بینٹی گوو 24 فروری 2016ہس منز رومس منز نمونیاہ...,چلے جاو تہٕ چکہٕ چاو سورٕنُک مطلب گونہٕ,ಓರ್ಸಂಡ್ ನ ಮೇಲುಭಾಗದ ಪ್ರದೇಶದಲ್ಲಿರುವ ಶಿಖರಪ್ರದೇಶದಲ...,Kashmiri
2207588,রাস্তায় শুয়ে থাকা শ্রমিকদের উপর দিয়ে চলে গে...,বেলো ৫ বার বিবাহ বন্ধনে আবদ্ধ হন ।,इस योजना दा लक्ष्य चरणबद्ध तरीके कन्नै शैह्री ...,Bangla
2207589,"यत्ते तव हे इन्द्र , बृहत् महत् ऊर्जितं वयो यौ...",मित्रभेद - मित्रप्राप्ति - काकोलूकीय - लब्धप्र...,தாலமி என்ற வானியல் நிபுணர் 48 விண்மீன் கூட்டங்...,Sanskrit

In [90]:
print(triplet_df["label"].value_counts())

# Calculate size in bytes → MB / GB
df_size_bytes = triplet_df.memory_usage(deep=True).sum()
df_size_mb = df_size_bytes / (1024 ** 2)
df_size_gb = df_size_bytes / (1024 ** 3)

print(f"\nTotal samples: {len(triplet_df):,}")
print(f"Languages included: {triplet_df['label'].nunique()}")
print(f"DataFrame size: {df_size_mb:.2f} MB ({df_size_gb:.3f} GB)")

label
Bodo         100345
Bangla       100345
Malayalam    100345
Urdu         100345
Tamil        100345
Marathi      100345
Hindi        100345
Kannada      100345
Telugu       100345
Punjabi      100345
Kashmiri     100345
Oriya        100345
Sindhi       100345
Manipuri     100345
Sanskrit     100345
Dogri        100345
Maithili     100345
Nepali       100345
Konkani      100345
Santali      100345
Gujarati     100345
Assamese     100345
Name: count, dtype: int64

Total samples: 2,207,590
Languages included: 22
DataFrame size: 1754.37 MB (1.713 GB)

In [91]:
triplet_df = triplet_df[['A','B','C']].rename(
    columns={'A': 'anchor','B': 'positive','C': 'negative'})
triplet_df.to_csv("triplet_native.csv", index=False)
print("NNN(type B) triplets are saved")

NNN(type B) triplets are saved

## Creating Phase 2 dataset

In [92]:
sampled_dfs = []

for lang, group in combined.groupby("label"): 
    sampled = group.sample(n=43005, random_state=31)
    sampled_dfs.append(sampled)

df = pd.concat(sampled_dfs, ignore_index=True)
print(df["label"].value_counts())

label
Assamese     43005
Bangla       43005
Bodo         43005
Dogri        43005
Gujarati     43005
Hindi        43005
Kannada      43005
Kashmiri     43005
Konkani      43005
Maithili     43005
Malayalam    43005
Manipuri     43005
Marathi      43005
Nepali       43005
Oriya        43005
Punjabi      43005
Sanskrit     43005
Santali      43005
Sindhi       43005
Tamil        43005
Telugu       43005
Urdu         43005
Name: count, dtype: int64

In [93]:
phase2_native = df[['native','label']].rename(columns={'native':'text'})
phase2_roman = df[['roman','label']].rename(columns={'roman':'text'})
phase2 = pd.concat([phase2_native, phase2_roman], axis=0, ignore_index=True)
phase2

                                                      text     label
0        উল্লেখ্য যে যোৱা ডিচেম্বৰত নতুন কৃষি আইনক কেন্...  Assamese
1        আয়োগক মুকলিভাৱে সমৰ্থন কৰা মাত্ৰ কেইজনমান ৰিপ...  Assamese
2        বাহ্যিক বস্তু সাধাৰণতে চকুৰ ওপৰ বা তলপতাৰ তলিত...  Assamese
3        তাৰোপৰি কেঁচা জলকীয়া , অমিতা , বিলাহী , অংকুৰ...  Assamese
4        এনে ৰোগত ৰোগীজনে বাস্তৱৰ লগত সম্পৰ্ক হেৰুৱাই ন...  Assamese
...                                                    ...       ...
1892215  subah khaibar pakhtunkhwa kay janub mein zalaa...      Urdu
1892216  aalimi saqafati warsah sights kaa yaha silsila...      Urdu
1892217  jnwb mshrq se jykbz lynr namy ayk khny pgnnny ...      Urdu
1892218  phwl awr pnkhe, ynny phwlwn se sjaie jane wale...      Urdu
1892219  rwayty nqydh yh he kh bche ky nrf se anhaiy ja...      Urdu

[1892220 rows x 2 columns]

In [94]:
print(phase2["label"].value_counts())

# Calculate size in bytes → MB / GB
df_size_bytes = phase2.memory_usage(deep=True).sum()
df_size_mb = df_size_bytes / (1024 ** 2)
df_size_gb = df_size_bytes / (1024 ** 3)

print(f"\nTotal samples: {len(phase2):,}")
print(f"Languages included: {phase2['label'].nunique()}")
print(f"DataFrame size: {df_size_mb:.2f} MB ({df_size_gb:.3f} GB)")
phase2.to_csv('phase2.csv', index=False)
print("Phase2 training dataset is saved")

label
Assamese     86010
Bangla       86010
Bodo         86010
Dogri        86010
Gujarati     86010
Hindi        86010
Kannada      86010
Kashmiri     86010
Konkani      86010
Maithili     86010
Malayalam    86010
Manipuri     86010
Marathi      86010
Nepali       86010
Oriya        86010
Punjabi      86010
Sanskrit     86010
Santali      86010
Sindhi       86010
Tamil        86010
Telugu       86010
Urdu         86010
Name: count, dtype: int64

Total samples: 1,892,220
Languages included: 22
DataFrame size: 516.70 MB (0.505 GB)
Phase2 training dataset is saved